### ISSUE TITLE
Create a classical connection channel structure

### ISSUE THREAD

**Issue by mgg39** [mgg39/qiskit-networks#10]
Most quantum networking simulating tools contain classical connection channels for node-to-node communication.
These channels are used to transmit security keys and other types of classical information within quantum network architectures. 
It would be useful to have an initial structure that we can build upon, that defines these classical channels within qiskit-networks.

See similar work for reference:
[SeQUeNCe](https://github.com/mgg39/SeQUeNCe)
[qiskrypt](https://github.com/mgg39/qiskrypt)

**Comment by poig** [comment]
[qiskrypt](https://github.com/mgg39/qiskrypt) is still empty, [netqasm](https://github.com/QuTech-Delft/netqasm) is a good reference also.

**Comment by grageragarces** [comment]
archived repository October 2023
