### ISSUE TITLE
List of idea (the purpose of this library)

### ISSUE THREAD

**Issue by poig** [mgg39/qiskit-networks#11]
- making something like [netqasm](https://github.com/QuTech-Delft/netqasm) structure of [SeQUeNCe](https://github.com/sequence-toolbox/SeQUeNCe), which allowed custom the action of each node and simplify the structure of the program, and include eavesdropper action
- do a class that can calculate the necessary parameter from the LONGITUDE ,LATITUDE and height from node, allowed visualize with the [Basemap](https://matplotlib.org/basemap/api/basemap_api.html#module-mpl_toolkits.basemap)(with this can interact with another file type like .nc), and simulate quantum satellite 
- visualize the divide qubit for each node in a device map & the animation of the communication process
- according to https://github.com/Qiskit/qiskit-metal/issues/389 & https://github.com/Qiskit/qiskit-metal/issues/135 we can think about how to connect qiskit metal with qiskit-network, which can simulate QRAM architecture and physical implementation

**Comment by poig** [comment]
@mgg39 what do you think about those ideas, is that doable?

**Comment by poig** [comment]
move dicussion to https://github.com/mgg39/qiskit-networks/discussions/12

**Comment by mgg39** [comment]
Hi @poig love these ideas an the continuation on the work in issue 12.Thank you for helping out!
