### ISSUE TITLE
Information reconciliation and privacy amplification

### ISSUE THREAD

**Issue by poig** [mgg39/qiskit-networks#8]
- [Mario Mastani](https://www.researchgate.net/publication/337901106_Non-ambiguity_quantum_teleportation_protocol) on Non-ambiguity teleportation protocol for entanglement pair generation and communication can lead to a better protocol with no or very minimal classical communication required.
- Brassard's approach -- the Cascade algorithm with binary search correction
- https://hikingandcoding.wordpress.com/2020/01/15/a-cascade-information-reconciliation-tutorial/
- [reference repository for the algorithm netqasm](https://github.com/upsideon/qkd-qchack-2022/tree/6c26b47765dcfe28d911c210877cb340d22ae5a5/noise) , [SeQUeNCe](https://github.com/sequence-toolbox/SeQUeNCe/blob/master/example/distance_cascade.py)

**Comment by mgg39** [comment]
Hi @poig , I am labeling this issue as future work, as we are yet to build more basic architectures of qiskit based networks before we proceed with this.
Thank you so much for your contribution, and feel free to help with the building of the component and program steps necessary to arrive to the point in which we can solve this issue.

**Comment by grageragarces** [comment]
archived repository October 2023
